---
- name: Aprovisionar VM con seguridad SSH
  hosts: all
  become: yes
  become_method: sudo
  remote_user: vagrant
  vars:
    ssh_public_key_path: "{{ lookup('env','HOME') }}/.ssh/dftd.pub"
  tasks:
    - import_tasks: ansible/ejercicio1/main.yml
    - import_tasks: ansible/ejercicio2/main.yml
    - import_tasks: ansible/ejercicio3/main.yml
    - import_tasks: ansible/ejercicio4/main.yml
    - import_tasks: ansible/ejercicio5/main.yml
    - import_tasks: ansible/ejercicio6/main.yml
    - import_tasks: ansible/ejercicio7/main.yml
    - import_tasks: ansible/ejercicio8/main.yml
    - import_tasks: ansible/ejercicio9/main.yml
    - import_tasks: ansible/ejercicio10/main.yml
    
  handlers:
    - import_tasks: handlers/main.yml