---
- name: Instalar prometheus
  apt:
    name: prometheus
    update_cache: yes
    state: present

- name: Configurar Prometheus para monitorear Node Exporter y Prometheus
  lineinfile:
    path: /etc/prometheus/prometheus.yml
    regexp: '^# scrape_configs'
    line: |
      scrape_configs:
        - job_name: 'prometheus'
          static_configs:
            - targets: ['localhost:9090']
        - job_name: 'node_exporter'
          static_configs:
            - targets: ['localhost:5000', 'localhost:9100']
    insertafter: '# scrape_configs'
    state: present
  notify:
    - Reiniciar Prometheus

- name: Instalar Node Exporter 
  apt:
    name: prometheus-node-exporter
    state: present

- name: Habilitar y iniciar Node Exporter
  systemd:
    name: prometheus-node-exporter
    state: started
    enabled: yes

- name: Descargar y añadir la clave GPG de Grafana
  ansible.builtin.shell: |
    curl -fsSL https://apt.grafana.com/gpg.key | gpg --dearmor -o /usr/share/keyrings/grafana-archive-keyring.gpg
  args:
    warn: false
  register: result

- name: Validar si la clave GPG fue añadida correctamente
  ansible.builtin.fail:
    msg: "Fallo al añadir la clave GPG de Grafana"
  when: result.rc != 0

- name: Agregar el repositorio oficial de Grafana
  ansible.builtin.copy:
    dest: /etc/apt/sources.list.d/grafana.list
    content: "deb [signed-by=/usr/share/keyrings/grafana-archive-keyring.gpg] https://packages.grafana.com/oss/deb stable main"
    notify: Actualizar apt

- name: Actualizar lista de paquetes
  apt:
    update_cache: yes

- name: Instalar Grafana
  apt:
    name: grafana
    state: present

- name: Iniciar y habilitar el servicio Grafana
  systemd:
    name: grafana-server
    state: started
    enabled: yes