---
- name: Instalar prometheus
  apt:
    name: prometheus
    update_cache: yes
    state: present

- name: Configurar Prometheus para monitorear Node Exporter y Prometheus
  lineinfile:
    path: /etc/prometheus/prometheus.yml
    regexp: '^# scrape_configs'
    line: |
      scrape_configs:
        - job_name: 'prometheus'
          static_configs:
            - targets: ['localhost:9090']
        - job_name: 'node_exporter'
          static_configs:
            - targets: ['localhost:5000', 'localhost:9100']
    insertafter: '# scrape_configs'
    state: present
  notify:
    - Reiniciar Prometheus

- name: Instalar Node Exporter 
  apt:
    name: prometheus-node-exporter
    state: present

- name: Habilitar y iniciar Node Exporter
  systemd:
    name: prometheus-node-exporter
    state: started
    enabled: yes

- name: Instalar Grafana
  apt:
    name: grafana
    state: present

- name: Iniciar y habilitar el servicio Grafana
  systemd:
    name: grafana-server
    state: started
    enabled: yes