---
- name: Actualizar e instalar paquetes del sistema
  apt:
    update_cache: yes
    name:
      - git
      - curl
    state: present

- name: Configurar locales a 'es_PE.UTF-8'
  locale_gen:
    name: 'es_PE.UTF-8'
    state: present

- name: Establecer locales del sistema
  lineinfile:
    path: /etc/default/locale
    regexp: '^LANG'
    line: 'LANG="es_PE.UTF-8"'

- name: Configurar zona horaria a 'America/Lima'
  timezone:
    name: America/Lima

- name: Crear el usuario 'devuser'
  user:
    name: devuser
    shell: /bin/bash
    password: "{{ 'brian' | password_hash('sha512') }}"

- name: Asegurar que el grupo 'admin' exista
  group:
    name: admin
    state: present

- name: Asignar 'devuser' al grupo 'admin'
  user:
    name: devuser
    groups: admin
    append: yes
